server:
  port: 8080

spring:   
  datasource:
    url: jdbc:mysql://140.143.224.40:3306/pdd_blog_v2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.qq.com
    username: 3334783376@qq.com
    password: bnssycirgiqydbjj
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  domain: http://localhost:8080/
  redis:
    database: 0
    host: 172.18.250.87
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 5000
mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml

logging:
  level:
    com.pdd.Blog.Mapper: debug

blog:
  cos:
    bucket: pdd-1255431832
    Region: ap-beijing
    SecretId: AKIDEI7i4BKkALJ2Xo4cNyLUQ9ew0rZ58cZG
    SecretKey: ZsvhDSRAdqnTu4yd4F9nAI9k5AzYqse9
    path: /avatar/